//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveApp.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveApp.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this business software ?.
        /// </summary>
        public static string BSVM_Delete {
            get {
                return ResourceManager.GetString("BSVM_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à example.exe.
        /// </summary>
        public static string Business_Example {
            get {
                return ResourceManager.GetString("Business_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 中国人 - Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to change the language to french ?.
        /// </summary>
        public static string Choice_ChangeLanguage {
            get {
                return ResourceManager.GetString("Choice_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to exit EasySave ?.
        /// </summary>
        public static string Choice_Confirm {
            get {
                return ResourceManager.GetString("Choice_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible to reach remote host.
        /// </summary>
        public static string CMW_HostUnreachable {
            get {
                return ResourceManager.GetString("CMW_HostUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remote host closed connection.
        /// </summary>
        public static string CNR_CloseConnection {
            get {
                return ResourceManager.GetString("CNR_CloseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete All.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete all business softwares ?.
        /// </summary>
        public static string DeleteBusinessVerif {
            get {
                return ResourceManager.GetString("DeleteBusinessVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete all extensions to crypt ?.
        /// </summary>
        public static string DeleteExtensionVerif {
            get {
                return ResourceManager.GetString("DeleteExtensionVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete all extensions to priorise ?.
        /// </summary>
        public static string DeletePriorityExtension {
            get {
                return ResourceManager.GetString("DeletePriorityExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select an extension.
        /// </summary>
        public static string ELF_Select {
            get {
                return ResourceManager.GetString("ELF_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fatal Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input cannot be empty.
        /// </summary>
        public static string Error_BusinessInvalidFormat {
            get {
                return ResourceManager.GetString("Error_BusinessInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : This business softawre is already in the list of business software.
        /// </summary>
        public static string Error_BusinessSoftware {
            get {
                return ResourceManager.GetString("Error_BusinessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A critical error has occured.
        /// </summary>
        public static string Error_Critical {
            get {
                return ResourceManager.GetString("Error_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid format (.example).
        /// </summary>
        public static string Error_ExtensionInvalidFormat {
            get {
                return ResourceManager.GetString("Error_ExtensionInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: The extension is already in the list of extensions to encrypte.
        /// </summary>
        public static string Error_ExtensionToCrypt {
            get {
                return ResourceManager.GetString("Error_ExtensionToCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : The extension is already in the list of extension to priorise.
        /// </summary>
        public static string Error_ExtensionToPriorise {
            get {
                return ResourceManager.GetString("Error_ExtensionToPriorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Neither Source or Target Path exist.
        /// </summary>
        public static string Error_NoPath {
            get {
                return ResourceManager.GetString("Error_NoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Source Path does not exist.
        /// </summary>
        public static string Error_NoSource {
            get {
                return ResourceManager.GetString("Error_NoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Target Path does not exist.
        /// </summary>
        public static string Error_NoTarget {
            get {
                return ResourceManager.GetString("Error_NoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Source path and target path can&apos;t be the same .
        /// </summary>
        public static string Error_SamePath {
            get {
                return ResourceManager.GetString("Error_SamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : This save name already exists..
        /// </summary>
        public static string Error_SameSaveName {
            get {
                return ResourceManager.GetString("Error_SameSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A save using the same source path is running. Stop or wait for it to finish before starting this one..
        /// </summary>
        public static string Error_SameSourcePath {
            get {
                return ResourceManager.GetString("Error_SameSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or several saves are still in progress. Stop or wait for them to finish before exiting the application..
        /// </summary>
        public static string Error_SaveInProgress {
            get {
                return ResourceManager.GetString("Error_SaveInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter Your Extension.
        /// </summary>
        public static string ETC_Ent {
            get {
                return ResourceManager.GetString("ETC_Ent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension.
        /// </summary>
        public static string ETC_Ext {
            get {
                return ResourceManager.GetString("ETC_Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this extension ?.
        /// </summary>
        public static string ETCVM_Delete {
            get {
                return ResourceManager.GetString("ETCVM_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .example.
        /// </summary>
        public static string Extension_Example {
            get {
                return ResourceManager.GetString("Extension_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target has correctly been created.
        /// </summary>
        public static string Info_CreatePath {
            get {
                return ResourceManager.GetString("Info_CreatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language is already in english.
        /// </summary>
        public static string Info_CurrentLanguage {
            get {
                return ResourceManager.GetString("Info_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The extension : has correctly been added to the list.
        /// </summary>
        public static string Info_ExtensionAdded {
            get {
                return ResourceManager.GetString("Info_ExtensionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The extension : has been defined as log file extension.
        /// </summary>
        public static string Info_LogExtension {
            get {
                return ResourceManager.GetString("Info_LogExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save : has correctly been added to the backup&apos;s list.
        /// </summary>
        public static string Info_SaveCreated {
            get {
                return ResourceManager.GetString("Info_SaveCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The software : has correctly been added to the list.
        /// </summary>
        public static string Info_SoftwareAdded {
            get {
                return ResourceManager.GetString("Info_SoftwareAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back-Ups.
        /// </summary>
        public static string Main_BU {
            get {
                return ResourceManager.GetString("Main_BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        public static string Main_Exit {
            get {
                return ResourceManager.GetString("Main_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your Path.
        /// </summary>
        public static string VBS_Ent {
            get {
                return ResourceManager.GetString("VBS_Ent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path.
        /// </summary>
        public static string VBS_Path {
            get {
                return ResourceManager.GetString("VBS_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a Back-Up.
        /// </summary>
        public static string VBU_Add {
            get {
                return ResourceManager.GetString("VBU_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this backup ?.
        /// </summary>
        public static string VBU_Delete {
            get {
                return ResourceManager.GetString("VBU_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string VBU_Edit {
            get {
                return ResourceManager.GetString("VBU_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string VBU_Start {
            get {
                return ResourceManager.GetString("VBU_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start all Back-Ups.
        /// </summary>
        public static string VBU_StartAll {
            get {
                return ResourceManager.GetString("VBU_StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        public static string VCBU_Complete {
            get {
                return ResourceManager.GetString("VCBU_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        public static string VCBU_Diff {
            get {
                return ResourceManager.GetString("VCBU_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string VCBU_Name {
            get {
                return ResourceManager.GetString("VCBU_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select save name.
        /// </summary>
        public static string VCBU_SelectN {
            get {
                return ResourceManager.GetString("VCBU_SelectN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select source path.
        /// </summary>
        public static string VCBU_SelectSP {
            get {
                return ResourceManager.GetString("VCBU_SelectSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Target Path.
        /// </summary>
        public static string VCBU_SelectTP {
            get {
                return ResourceManager.GetString("VCBU_SelectTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source Path.
        /// </summary>
        public static string VCBU_SP {
            get {
                return ResourceManager.GetString("VCBU_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target Path.
        /// </summary>
        public static string VCBU_TP {
            get {
                return ResourceManager.GetString("VCBU_TP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to modify max file size value ?.
        /// </summary>
        public static string VIFS_AddConfirmation {
            get {
                return ResourceManager.GetString("VIFS_AddConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max file size value for simultaneous save files is now : Kb.
        /// </summary>
        public static string VIFS_Confirm {
            get {
                return ResourceManager.GetString("VIFS_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Field cannot be empty.
        /// </summary>
        public static string VIFS_ErrorEmpty {
            get {
                return ResourceManager.GetString("VIFS_ErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max Size.
        /// </summary>
        public static string VIFS_MaxSize {
            get {
                return ResourceManager.GetString("VIFS_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a proper value (byte).
        /// </summary>
        public static string VIFS_Value {
            get {
                return ResourceManager.GetString("VIFS_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set prioritary extensions.
        /// </summary>
        public static string VP_SetPE {
            get {
                return ResourceManager.GetString("VP_SetPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business Software.
        /// </summary>
        public static string VS_BS {
            get {
                return ResourceManager.GetString("VS_BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension To Crypt.
        /// </summary>
        public static string VS_ExtCrypt {
            get {
                return ResourceManager.GetString("VS_ExtCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log File Extension.
        /// </summary>
        public static string VS_LogFile {
            get {
                return ResourceManager.GetString("VS_LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max simultaneous files size .
        /// </summary>
        public static string VS_MaxSize {
            get {
                return ResourceManager.GetString("VS_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priority Files.
        /// </summary>
        public static string VS_PF {
            get {
                return ResourceManager.GetString("VS_PF", resourceCulture);
            }
        }
    }
}
